name: Tetris DevSecOps Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  GIT_REPO_NAME: "End-to-End-Kubernetes-DevSecOps-Tetris-Project"
  GIT_USER_NAME: "dragerzw"
  IMAGE_NAME: "realdrager/tetrisv1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '18'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: Tetris-V2
          args: >
            -Dsonar.projectName=Tetris
            -Dsonar.projectKey=Tetris

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Node Dependencies
        working-directory: ./Tetris-V2
        run: npm install

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main # v1.1.0
        with:
          project: 'Tetris'
          path: './Tetris-V2'
          format: 'ALL'
          additionalArguments: '--disableYarnAudit --disableNodeAudit'

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0 (SAFE SHA)
        with:
          scan-type: 'fs'
          scan-ref: './Tetris-V2'
          format: 'table'
          output: 'Tetris-V2/trivyfs.txt'

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: ./Tetris-V2
        run: |
          docker system prune -f
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.run_number }} .
          docker push ${{ env.IMAGE_NAME }}:${{ github.run_number }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0 (SAFE SHA)
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.run_number }}'
          format: 'table'
          output: 'trivyimage.txt'

      - name: Update Kubernetes Deployment Manifest
        working-directory: ./Manifest-file
        run: |
          git config user.email "dragerzw@users.noreply.github.com"
          git config user.name "dragerzw"
          
          echo "Build Number: ${{ github.run_number }}"
          imageTag=$(grep -oP '(?<=tetrisv1:)[^ ]+' deployment-service.yml)
          echo "Current Tag: $imageTag"
          
          sed -i "s/tetrisv1:${imageTag}/tetrisv1:${{ github.run_number }}/" deployment-service.yml
          git add deployment-service.yml
          git commit -m "Update deployment Image to version ${{ github.run_number }}"
          git push https://${{ secrets.GH_PAT_TOKEN }}@github.com/${{ env.GIT_USER_NAME }}/${{ env.GIT_REPO_NAME }}.git HEAD:master